### ISSUE TITLE
Issues with README.md

### ISSUE THREAD

**Issue by linKhehe** [Daggy1234/dagpi#2]
I think the current README is a good start; however, with a few changes to it's current format and grammar, which is lacking in both writing skill and creativeness, it could really pop and add a lot to this project. As we all know, one of the first things you see then you click on a GitHub repository is the README, this is why it's so important. Currently, as of June 22, 2020, there are 100+ pull requests that all have their own unique suggestions and additions for the README, but one just takes the cake. That pull request would be the one submitted by @ir-3. It provides more accurate information while also increasing the readers want to continue reading the article. I request that you wholeheartedly take this pull request's suggestions into your large pool of consideration for your elegant and powerful API. 

Thank you for your time,
Liam (ir-3) H.

P.S. Here is the url linking you to the pull request that I mention throughout this suggestion, again, thanks for your time. #1

**Comment by daggy1234** [comment]
Okay thanks for the pull request, but the readme while inaccurate, tries to display what we hope the API will aspire and achieve. I am deeply sorry If I hurt your feelings, but your pull request is inaccurate as while we may in no way be N1,

- The number `4,137th` is insultinglu high for a bot that is in the low 10,000's.

- The API framework is FastAPI and not SlowAPI

- As a non-user of the API I do not think you have understood and or used the API, and would suggest trying it before calling it slow

- Also the current dagbot is barely able to manipulate gifs as it runs on a slower and older API. Please wait for the re-write before talking about the gif capability.

- Also yes my naming sucks, and we are ready to rename dagpi!

Thank you for your time!

**Comment by Daggy1234** [comment]
@chr1s

**Comment by daggy1234** [comment]
Okay then lets meet in the middle

**Comment by daggy1234** [comment]
@crrapi @ir-3 @equity 
Can we settle,
we  can say 7312th Meme Bot
FastAPI remains because that is the framework
As for the ability we can say: Successfully manipulate? (Speed is meh)

**Comment by crrapi** [comment]
> Successfully manipulate

I'd say the success rate is a solid 30%

**Comment by daggy1234** [comment]
@crrapi cool then reflect the changes in the new ReadMe and I'll merge

**Comment by daggy1234** [comment]
@crrapi cool then reflect the changes in the new ReadMe and I'll merge

**Comment by crrapi** [comment]
THIS REPOSITORY HAS BEEN HACK BY MONOX

**Comment by daggy1234** [comment]
mega F
